### ISSUE TITLE
Not working with webpack and babel

### ISSUE THREAD

**Issue by JM-Mendez** [jscrambler/jscrambler-loader#1]
I was testing out this service, but I'm developing with react and using babel. Jscrambler throws token errors without babel-loader, but won't accept the input from babel-loader throwing a "no source files found" error in zip.js. Any chance you can look at this? Here's my relevant config.

```
module: {
    rules: [{
      test: /\.jsx?$/,
      exclude: /node_modules/,
      use: [{
        loader: 'jscrambler-loader'
      }, {
        loader: 'babel-loader',
        options: {
          cacheDirectory: true
        },
      }]
    }]
  },
```

**Comment by CMatias** [comment]
Hi @JM-Mendez , we're sorry to hear that. We will be looking into this and also updating the documentation to address webpack 2. 

In the meantime please use our [CLI Tool](https://github.com/jscrambler/javascript-jscrambler).
